# Site settings
title: Benno's Blog
email: bennokr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AI demos
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bennokr.github.io" # the base hostname & protocol for your site
twitter_username: bennokruit
github_username:  bennokr

# Build settings
markdown: redcarpet
